### ISSUE TITLE
Kernel `windows` not known to work with OS `gnu`

### ISSUE THREAD

**Issue by jafri** [tov/libffi-rs#60]
On M1 Mac, running rust with target x86_64-pc-windows-gnu
  
  ```
  process didn't exit successfully: `target/release/build/libffi-sys-7f2a7ab9ea025606/build-script-build` (exit status: 101)
  --- stdout
  checking build system type... aarch64-apple-darwin21.6.0
  checking host system type... 
  --- stderr
  Invalid configuration `x86_64-pc-windows-gnu': Kernel `windows' not known to work with OS `gnu'.
  configure: error: /bin/sh ./config.sub x86_64-pc-windows-gnu failed
  thread 'main' panicked at 'Configuring libffi', /.cargo/registry/src/github.com-1ecc6299db9ec823/libffi-sys-2.0.1/build/common.rs:8:5
  
 ```
 
 Backtrace
 
 ```
   stack backtrace:
     0: rust_begin_unwind
               at /rustc/95a3a7277b44bbd2dd3485703d9a05f64652b60e/library/std/src/panicking.rs:575:5
     1: core::panicking::panic_fmt
               at /rustc/95a3a7277b44bbd2dd3485703d9a05f64652b60e/library/core/src/panicking.rs:65:14
     2: core::panicking::panic_display
     3: build_script_build::common::run_command
     4: build_script_build::not_msvc::configure_libffi
     5: build_script_build::not_msvc::build_and_link
     6: build_script_build::main
     7: core::ops::function::FnOnce::call_once
```

**Comment by YorickPeterse** [comment]
@jafri Please provide some sample program that can reproduce this problem, along with the exact command used to compile it. A backtrace alone isn't enough to debug (cross) compilation problems.

**Comment by YorickPeterse** [comment]
@jafri This is a friendly reminder to please provide a way to reproduce this issue. Without it there's nothing we can do to help.

**Comment by jafri** [comment]
Was not able to reproduce

**Comment by CyanChanges** [comment]
> [@jafri](https://github.com/jafri) Please provide some sort of sample program that reproduces this problem, along with the exact command used to compile it. A backtrace alone isn't enough to debug (cross) compilation problems 😃

Trying to build `done`:
https://github.com/CyanProjects/done.git
```shell
$ rustup target add x86_64-pc-windows-msvc
$ V8_FROM_SOURCE=1 RUST_BACKTRACE=1 cargo build --release -v --target x86_64-pc-windows-gnu
```

**Comment by CyanChanges** [comment]
@yorickpeterse

**Comment by emiltayl** [comment]
This should be fixed by https://github.com/tov/libffi-rs/pull/118, so should work once the a version with the pull request is released.

**Comment by arihant2math** [comment]
`libffi-sys` is going to be bumped, so we'll see.

**Comment by arihant2math** [comment]
Alright bumped it, ping me if it persists.
