### ISSUE TITLE
Build error in vscode dev container

### ISSUE THREAD

**Issue by DreamTexX** [tov/libffi-rs#71]
I run into errors when trying to build/use the library in a nightly project inside an docker container (visual studio code dev container).

Cargo tells me the following when trying to build.

```
error: failed to run custom build command for `libffi-sys v2.1.0`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/workspaces/serverless/target/debug/build/libffi-sys-5ecfe1cce31411db/build-script-build` (exit status: 101)
  --- stdout
  checking build system type... x86_64-pc-linux-gnu
  checking host system type... x86_64-pc-linux-gnu
  checking target system type... x86_64-pc-linux-gnu
  continue configure in default builddir "./x86_64-unknown-linux-gnu"
  ....exec /bin/bash ../configure "--srcdir=.." "--enable-builddir=x86_64-unknown-linux-gnu" "linux
  gnu"

  --- stderr
  ../configure: line 2251: config.log: No such file or directory
  ../configure: line 2261: config.log: No such file or directory
  cat: standard output: No such file or directory
  thread 'main' panicked at 'Configuring libffi', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/libffi-sys-2.1.0/build/common.rs:8:5
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/2036fdd24f77d607dcfaa24c48fbe85d3f785823/library/std/src/panicking.rs:577:5
     1: core::panicking::panic_fmt
               at /rustc/2036fdd24f77d607dcfaa24c48fbe85d3f785823/library/core/src/panicking.rs:67:14
     2: core::panicking::panic_display
     3: build_script_build::common::run_command
     4: build_script_build::not_msvc::configure_libffi
     5: build_script_build::not_msvc::build_and_link
     6: build_script_build::main
     7: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Versions:
```
rustc 1.70.0-nightly (2036fdd24 2023-03-27)
cargo 1.70.0-nightly (145219a9f 2023-03-27)
```

Environment:
```
Container Image: mcr.microsoft.com/devcontainers/rust:0-1-bullseye
(Guess it is debian because of the bullseye)
```

If any other information is needed, please tell me. It builds finde on my linux machine (arch) and on windows direct, only inside the container it does not build.

**Comment by yorickpeterse** [comment]
Judging by the output it seems the build system thinks the environment is a Linux environment, but perhaps Microsoft is stripping the commands/dependencies needed to run the `configure` script. Unfortunately I don't think there's anything we can help with here, as we don't control the container image in question.

**Comment by yorickpeterse** [comment]
Closing this because there's nothing that we can do about this as far as I can tell.
